services:
  softether-server:
    image: siomiz/softethervpn
    cap_add:
      - NET_ADMIN
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
      - 5555:5555/tcp
    container_name: softether-server
    environment:
      - USERNAME=hihumikan
      - PASSWORD=vpnpassword
      - PSK=vpnsecret
